# Generated by Django 3.0.4 on 2020-04-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='goodspic/')),
                ('start_city', models.CharField(max_length=100)),
                ('end_city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('good_name', models.CharField(max_length=100)),
                ('offer_price', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
            ],
        ),
    ]
