# Generated by Django 3.0.4 on 2020-04-05 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_uploadimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Uploadimage',
            new_name='AddNeeds',
        ),
    ]
