# Generated by Django 3.0.4 on 2020-04-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200406_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='addneeds',
            name='placeorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addneeds',
            name='user',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addservice',
            name='placeorder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='addservice',
            name='user',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addneeds',
            name='image',
            field=models.ImageField(blank=True, default='needspic/default_img.jpg', upload_to='needspic/'),
        ),
        migrations.AlterField(
            model_name='addservice',
            name='image',
            field=models.ImageField(blank=True, default='servicepic/default_img.jpg', upload_to='servicepic/'),
        ),
    ]
