# Generated by Django 3.0.4 on 2020-04-07 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200406_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addneeds',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='addservice',
            options={'managed': False},
        ),
    ]
