# Generated by Django 3.0.4 on 2020-04-07 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200407_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addneeds',
            options={},
        ),
        migrations.AlterModelOptions(
            name='addservice',
            options={},
        ),
    ]
