# Generated by Django 3.0.4 on 2020-04-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200407_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='addneeds',
            name='orderstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addneeds',
            name='orderuser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addservice',
            name='orderstatus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='addservice',
            name='orderuser',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
