# Generated by Django 3.0.4 on 2020-04-10 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservice',
            old_name='start_city',
            new_name='old_start_city',
        ),
    ]
