# Generated by Django 3.0.4 on 2020-04-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200410_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='addservice',
            name='start_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City'),
        ),
    ]
