# Generated by Django 3.0.4 on 2020-04-11 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_addservice_start_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='servicepic/default_img.jpg', upload_to='servicepic/')),
                ('old_start_city', models.CharField(blank=True, max_length=100)),
                ('end_city', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ask_price', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('orderuser', models.CharField(max_length=100, null=True)),
                ('orderstatus', models.IntegerField(default=0)),
                ('isDeleteByUser', models.BooleanField(default=False)),
                ('isDeleteByOrderUser', models.BooleanField(default=False)),
                ('start_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.City')),
            ],
        ),
        migrations.DeleteModel(
            name='AddService',
        ),
    ]
