# Generated by Django 3.0.4 on 2020-04-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200411_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddNeeds',
            new_name='Needs',
        ),
    ]
