# Generated by Django 3.0.4 on 2020-04-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20200411_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Needs',
            new_name='Need',
        ),
    ]
