# Generated by Django 3.0.4 on 2020-04-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200411_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='status_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='status_name',
            field=models.CharField(default='completed', max_length=100),
        ),
    ]
