# Generated by Django 3.0.4 on 2020-04-11 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20200411_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='need',
            name='end_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_end_city', to='users.City'),
        ),
        migrations.AlterField(
            model_name='need',
            name='orderstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='need_orderstatus', to='users.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='need',
            name='start_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_start_city', to='users.City'),
        ),
        migrations.AlterField(
            model_name='need',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='need_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='end_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_end_city', to='users.City'),
        ),
        migrations.AlterField(
            model_name='service',
            name='orderstatus',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='service_orderstatus', to='users.OrderStatus'),
        ),
        migrations.AlterField(
            model_name='service',
            name='start_city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_start_city', to='users.City'),
        ),
        migrations.AlterField(
            model_name='service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
