# Generated by Django 3.0.4 on 2020-04-21 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20200411_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='offer_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='service',
            name='ask_price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
